variable "do_token" {
  description = "DigitalOcean API token"
  type        = string
  sensitive   = true
  default     = ""
}

# Note: Domain and records are read from resend-config.json
# This file is generated by the Node.js create-domain script
