services:
  reverse-proxy-certonly:
    image: nginx:alpine
    container_name: reverse_proxy_for_certbot
    configs:
      - source: nginx_certonly_conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      reverse-proxy-certonly:
        condition: service_started
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: >
      certonly -vvv --webroot
      --webroot-path=/var/www/html
      --email jakob.lingel@hotmail.de
      --agree-tos --no-eff-email
      --cert-name legit-certificate
      -d admin.schluesselmomente-freiburg.de
      -d jakob-lingel.dev
      -d immoly.jakob-lingel.dev

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    depends_on: 
      certbot:
        condition: service_completed_successfully
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    ports:
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # if the certificate has expired, uncomment the below line and run "docker compose up -d"
      - web-root:/var/www/html
    networks:
      - app-network

configs:
  nginx_conf:
    file: ./nginx.conf
  nginx_certonly_conf:
    file: ./nginx.certonly.conf

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local

networks:
  app-network:
    name: app-network
    external: true
